### ISSUE TITLE
What is this used for?

### ISSUE THREAD

**Issue by DavidZyy** [chipsalliance/espresso#28]
Can anyone tell me what is this used for? This project has no README and description.

**Comment by mwachs5** [comment]
https://github.com/chipsalliance/espresso/blob/master/doc/espresso.adoc

**Comment by sequencer** [comment]
This project is used in [Chisel](https://github.com/chipsalliance/chisel/blob/8b4834f00307d4e99de64f3441de8068b08bac51/src/main/scala/chisel3/util/experimental/decode/decoder.scala#L60-L85) for [logic minimization](https://en.wikipedia.org/wiki/Logic_optimization)
Since it's not actively maintained in chipsaliance(forked from [berkeley](https://ptolemy.berkeley.edu/projects/embedded/pubs/downloads/espresso/index.htm)), see this commit: https://github.com/chipsalliance/espresso/commit/52a94dde27426a6d17af90904264c8491b7c6534
